{{- if .Values.db.adminPassword }}
{{- if .Capabilities.APIVersions.Has "kci.rocks/v1alpha1" }}
apiVersion: kci.rocks/v1alpha1
kind: Database
metadata:
  name: {{ include "dummy-service.fullname" . }}
spec:
  secretName: {{ include "dummy-service.fullname" . }}-db # DB Operator will generate secret with this name if not specified. it contains db name, user, password
  instance: {{ include "dummy-service.fullname" . }}
  deletionProtected: true # Protection to not delete database when custom resource is deleted
  backup:
    enable: false # turn it to true when you want to use back up feature. currently only support postgres
    cron: "0 0 * * *"
{{- end }}
{{- end }}
