apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dummy-service.fullname" . }}
  labels:
    {{- include "dummy-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dummy-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dummy-service.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "dummy-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /actuator/health
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /actuator/info
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
         # volumeMounts:
         #   - name: {{ include "dummy-service.fullname" . }}
         #     mountPath: /etc/nginx/conf.d/default.conf
         #     subPath: default.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
     # volumes:
     #   - name: {{ include "dummy-service.fullname" . }}
     #     configMap:
     #       name: {{ include "dummy-service.fullname" . }}
