apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dummy-service.fullname" . }}
  labels:
    {{- include "dummy-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dummy-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dummy-service.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "dummy-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:

            ## Endpoints
            - name: CONTROLLER_ECHOSERVER_URL
              value: "{{ .Values.controller.echoserver.url }}"
            - name: CONTROLLER_HTTPCLIENT_URL
              value: "{{ .Values.controller.httpclient.url }}"
            - name: CONTROLLER_HOTROD_URL
              value: "{{ .Values.controller.hotrod.url }}"
            - name: CONTROLLER_DB_URL
              value: "{{ .Values.controller.db.url }}"

            ## DB Auth
            - name: SPRING_DATASOURCE_URL
              value: "{{ tpl .Values.db.jdbcUrl . }}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "dummy-service.fullname" . }}-db
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dummy-service.fullname" . }}-db
                  key: POSTGRES_PASSWORD

            ## Infinispan Auth
            - name: INFINISPAN_REMOTE_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "dummy-service.fullname" . }}-infinispan
                  key: username
            - name: INFINISPAN_REMOTE_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dummy-service.fullname" . }}-infinispan
                  key: password
            ## Infinispan TLS Settings
            - name: INFINISPAN_REMOTE_USE_SSL
              value: "true"
            - name: INFINISPAN_REMOTE_KEY_STORE_FILE_NAME
              value: "/app/config/pkcs12/keystore.p12"
            - name: INFINISPAN_REMOTE_KEY_STORE_TYPE
              value: pkcs12
            - name: INFINISPAN_REMOTE_KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dummy-service.fullname" . }}-infinispan-keystore
                  key: password-key
            - name: INFINISPAN_REMOTE_TRUST_STORE_FILE_NAME
              value: "/app/config/pkcs12/truststore.p12"
            - name: INFINISPAN_REMOTE_TRUST_STORE_TYPE
              value: pkcs12
            - name: INFINISPAN_REMOTE_TRUST_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dummy-service.fullname" . }}-infinispan-keystore
                  key: password-key


          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /actuator/health
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /actuator/info
          #    port: http
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
         # volumeMounts:
         #   - name: {{ include "dummy-service.fullname" . }}
         #     mountPath: /etc/nginx/conf.d/default.conf
         #     subPath: default.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
     # volumes:
     #   - name: {{ include "dummy-service.fullname" . }}
     #     configMap:
     #       name: {{ include "dummy-service.fullname" . }}
