apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "dummy-service.fullname" . }}-keystore
spec:
  secretName: {{ include "dummy-service.fullname" . }}-keystore
  dnsNames:
  - {{ include "dummy-service.fullname" . }}
  - {{ include "dummy-service.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "dummy-service.fullname" . }}.{{ .Release.Namespace }}{{ .Values.global.fqdnSuffix }}
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-ca-issuer
  keystores:
    ## It is preferable to use PKSC12 format instead of proprietary JKS format
    #jks:
    #  create: true
    #  passwordSecretRef: # Password used to encrypt the keystore
    #    key: password-key
    #    name: {{ include "dummy-service.fullname" . }}-keystore-creds
    pkcs12:
      create: true
      passwordSecretRef: # Password used to encrypt the keystore
        key: password-key
        name: {{ include "dummy-service.fullname" . }}-keystore-creds
