apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "dummy-service.fullname" . }}-admin-db

stringData:
  user: {{ .Values.db.adminUsername | quote }}
  password: {{ .Values.db.adminPassword | quote }}

