apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "dummy-service.fullname" . }}-infinispan

stringData:
  username: {{ .Values.infinispan.username | quote }}
  password: {{ .Values.infinispan.password | quote }}

