apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "dummy-service.fullname" . }}-db
stringData:
  POSTGRES_DB: {{ .Values.db.name }}
  POSTGRES_USER: {{ .Values.db.username }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
