{{- if .Values.db.adminPassword }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "dummy-service.fullname" . }}-db-admin

stringData:
  user: {{ .Values.db.adminUsername | quote }}
  password: {{ .Values.db.adminPassword | quote }}
{{- end }}