apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dummy-service.serviceAccountName" . }}
  labels:
    {{- include "dummy-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
