name: Build Image

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

## My ENV vars
env:
  IMAGE_NAME: dummy-service

permissions: ## https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview
  #id-token: write
  #contents: read
  #issues: write
  #pull-requests: write
  checks: write  ## fixed an Error: HttpError: Resource not accessible by integration: https://github.com/dorny/test-reporter/issues/149#issuecomment-1004820190
  packages: write ## fixed an Error: failed to push ghcr.io/vladimir22/dummy-service:latest: unexpected status: 403 Forbidden

  
jobs:
  build:
    runs-on: ubuntu-latest

    ## self-hosted run: https://github.com/vladimir22/dummy-service/settings/actions/runners
    #runs-on: self-hosted ## run it locally: ~/actions-runner/run.sh

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3 ## configures the Eclipse Temurin (Java) 17 JDK by Eclipse Adoptium.
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Maven Build ## runs the Maven package target in non-interactive mode to ensure that your code builds, tests pass, and a package can be created.
      run: |
        pwd
        cd dummy-service
        mvn --batch-mode -DskipTests package

    - name: Maven Test
      run: |
        pwd
        cd dummy-service
        mvn --batch-mode -Dmaven.test.failure.ignore=true test

    - name: Test Report
      uses: dorny/test-reporter@v1 ## https://octopus.com/blog/githubactions-running-unit-tests
      if: always() ## Generate the report even if the Test step above was set to fail in the event of failed tests.
      with:
        name: Maven Tests
        path: dummy-service/target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true

    - name: Get Docker Metadata 
      id: meta
      uses: docker/metadata-action@v4 ## https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/vladimir22/dummy-service
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
   
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1 ## https://github.com/qemu/qemu#qemu-readme

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1    

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }} ## https://github.com/settings/tokens
        password: ${{ secrets.GITHUB_TOKEN }} ## https://github.com/vladimir22/dummy-service/settings/secrets/actions

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        #push: true
        #tags: ghcr.io/vladimir22/dummy-service:latest ## important to specify right host 'ghcr.io' and username otherwise docker.io used !!!
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: .
