name: Build Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

## My ENV vars
env:
  IMAGE_NAME: dummy-service

permissions: ## https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview
  id-token: write
  contents: read
  issues: write
  pull-requests: write
  checks: write  ## fixed an Error: HttpError: Resource not accessible by integration: https://github.com/dorny/test-reporter/issues/149#issuecomment-1004820190

  
jobs:
  build:

    runs-on: ubuntu-latest

    ## My runner is self-hosted: https://github.com/vladimir22/dummy-service/settings/actions/runners
    #runs-on: self-hosted ## run it locally: ~/actions-runner/run.sh

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3 ## configures the Eclipse Temurin (Java) 17 JDK by Eclipse Adoptium.
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

    - name: Report ## https://octopus.com/blog/githubactions-running-unit-tests
      uses: dorny/test-reporter@v1
      if: always() ## generate the report even if the Test step above was set to fail in the event of failed tests.
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1 ## https://github.com/qemu/qemu#qemu-readme

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1    

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }} ## https://github.com/settings/tokens
        password: ${{ secrets.GITHUB_TOKEN }} ## https://github.com/vladimir22/dummy-service/settings/secrets/actions

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: ghcr.io/vladimir22/dummy-service:latest ## important to specify right host 'ghcr.io' and username otherwise docker.io used !!!
    
