name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

## My ENV vars
env:
  IMAGE_NAME: dummy-service
  
jobs:
  build:
    ## My runner is self-hosted: https://github.com/vladimir22/dummy-service/settings/actions/runners
    runs-on: self-hosted ## run it locally: ~/actions-runner/run.sh

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1 ## https://github.com/qemu/qemu#qemu-readme
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }} ## https://github.com/settings/tokens
        password: ${{ secrets.GITHUB_TOKEN }} ## https://github.com/vladimir22/dummy-service/settings/secrets/actions

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: ghcr.io/vladimir22/dummy-service:latest,ghcr.io/vladimir22/dummy-service:${{ github.event.release.tag_name }} ## important to specify right host 'ghcr.io' and username otherwise docker.io used !!!
    
